---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tg-app-configmap
data:
  .env: |
    TELEGRAM_BOT_TOKEN=6723856872:AAEV_pwdszZ5vkcQphF7z7CyR_SqAkidj8U
    MESSENGER_TRANSPORT_DSN=amqp://user:password@rabbitmq-clusterip:5672/%2f
    DATABASE_URL="postgresql://postgres:123456@tg-postgres-clusterip:5432/tg-bot?serverVersion=16&charset=utf8"
    APP_BOT_LISTENER_HTTP_HOST="http://nc-api"
    APP_BOT_LISTENER_HTTP_ROUTE="/api/inner/telegram-bot/handle-update"
    APP_BOT_LISTENER_HTTP_HEADER="{}"
