---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tg-consumer-configmap
data:
  consumer.conf: |
    [program:tg-consumer-defualt]
    command=php bin/console messenger:consume default -vv
    directory=/var/www/html
    autostart=true
    autorestart=unexpected
    exitcodes=0
    startretries=99999
    startsecs=0
    user=root
    numprocs=10
    process_name=%(program_name)s_%(process_num)02d
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    stderr_logfile_maxbytes=0

    [program:tg-consumer-accept-updates]
    command=php bin/console messenger:consume accept-updates -vv
    directory=/var/www/html
    autostart=true
    autorestart=unexpected
    exitcodes=0
    startretries=99999
    startsecs=0
    user=root
    numprocs=10
    process_name=%(program_name)s_%(process_num)02d
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    stderr_logfile_maxbytes=0

    [program:tg-consumer-accept-api]
    command=php bin/console messenger:consume api -vv
    directory=/var/www/html
    autostart=true
    autorestart=unexpected
    exitcodes=0
    startretries=99999
    startsecs=0
    user=root
    numprocs=10
    process_name=%(program_name)s_%(process_num)02d
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
