version: '3.9'

services:
  proxy:
    container_name: stgbot_proxy
    image: nginx:stable
    command: ['nginx', '-g', 'daemon off;']
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - app-volume:/var/www/html
    networks:
      - stgbot-network

  fpm:
    container_name: stgbot_fpm
    image: symfony-react:7-18-8.3-dev
    command: ['php-fpm']
    environment:
      - APP_ENV=dev
    ports:
      - '9000:9000'
    volumes:
      - app-volume:/var/www/html
    networks:
      - stgbot-network

volumes:
  app-volume:

networks:
  stgbot-network:
    external: true
