<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240605115522 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE telegram_bot_update_response (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, telegram_bot_update_id BIGINT NOT NULL, telegram_bot_message_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F14C2685B769BA0CE6C82348 ON telegram_bot_update_response (telegram_bot_update_id, telegram_bot_message_id)');
        $this->addSql('CREATE INDEX IDX_F14C2685E6C82348 ON telegram_bot_update_response (telegram_bot_message_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE telegram_bot_update_response');
    }
}
