<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240605093457 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE telegram_bot_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(100) NOT NULL, chat_id INT NOT NULL, data JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_sent BOOLEAN DEFAULT false NOT NULL, priority SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F9C9D5C98CDE5729 ON telegram_bot_message (type)');
        $this->addSql('CREATE INDEX IDX_F9C9D5C91A9A7125 ON telegram_bot_message (chat_id)');
        $this->addSql('CREATE INDEX IDX_F9C9D5C98B8E8428 ON telegram_bot_message (created_at)');
        $this->addSql('CREATE INDEX IDX_F9C9D5C92F370488 ON telegram_bot_message (is_sent)');
        $this->addSql('CREATE INDEX IDX_F9C9D5C962A6DC27 ON telegram_bot_message (priority)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE telegram_bot_message');
    }
}
